export const dashboardNavigation = [
  { title: "Overview", href: "/dashboard" },
  { title: "Clients", href: "/dashboard/clients" },
  { title: "Leads", href: "/dashboard/leads" },
  { title: "Projects", href: "/dashboard/projects" },
  { title: "Tasks", href: "/dashboard/tasks" },
  { title: "Calendar", href: "/dashboard/calendar" },
  { title: "Documents", href: "/dashboard/documents" },
  { title: "Search", href: "/dashboard/search" },
  { title: "Reports", href: "/dashboard/reports" },
  { title: "Marketing", href: "/dashboard/marketing" },
  { title: "SEO", href: "/dashboard/seo" },
  { title: "Advertising", href: "/dashboard/advertising" },
  { title: "AI Studio", href: "/dashboard/ai-studio" },
  { title: "Finance", href: "/dashboard/finance" },
  { title: "Client Portal", href: "/dashboard/client-portal" },
  { title: "Agency Portal", href: "/dashboard/agency-portal" },
  { title: "Notifications", href: "/dashboard/notifications" },
  { title: "Integrations", href: "/dashboard/integrations" },
  { title: "Import / Export", href: "/dashboard/import-export" },
  { title: "Enterprise Settings", href: "/dashboard/platform-settings" },
  { title: "Profile", href: "/settings/profile" },
  { title: "Organization", href: "/settings/organization" },
  { title: "Team", href: "/settings/team" },
  { title: "Roles", href: "/settings/roles" },
] as const;
