-- Sydora AI OS: tenant-aware CRM and marketing data foundation.
create extension if not exists "pgcrypto";
create schema if not exists private;

create type public.member_role as enum ('owner', 'admin', 'member', 'viewer');
create type public.lifecycle_status as enum ('active', 'inactive', 'archived');
create type public.project_status as enum ('planned', 'active', 'on_hold', 'completed', 'cancelled');
create type public.task_status as enum ('todo', 'in_progress', 'blocked', 'done');
create type public.priority as enum ('low', 'medium', 'high', 'urgent');
create type public.campaign_status as enum ('draft', 'active', 'paused', 'completed');
create type public.campaign_channel as enum ('email', 'search', 'social', 'content', 'other');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text not null default '', avatar_url text, timezone text not null default 'UTC', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz);
create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null check (char_length(name) between 2 and 160), slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid not null references auth.users(id), deleted_at timestamptz);
create table public.roles (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), name text not null check (char_length(name) between 2 and 80), description text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz, unique (organization_id, name));
create table public.permissions (id uuid primary key default gen_random_uuid(), key text not null unique check (key ~ '^[a-z0-9_.]+$'), description text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz);
create table public.organization_members (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), user_id uuid not null references auth.users(id), role_id uuid references public.roles(id), member_role public.member_role not null default 'member', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz, unique (organization_id, user_id));
create table public.role_permissions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), role_id uuid not null references public.roles(id) on delete cascade, permission_id uuid not null references public.permissions(id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz, unique (role_id, permission_id));
create table public.subscription_plans (id uuid primary key default gen_random_uuid(), code text not null unique, name text not null, monthly_price numeric(12,2) not null default 0 check (monthly_price >= 0), limits jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz);
create table public.organization_subscriptions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), plan_id uuid not null references public.subscription_plans(id), status text not null check (status in ('trialing','active','past_due','cancelled')), starts_at timestamptz not null default now(), ends_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz);
create table public.settings (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), key text not null, value jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz, unique (organization_id, key));

create table public.clients (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), name text not null check (char_length(name) between 2 and 160), website text, industry text, lifecycle_status public.lifecycle_status not null default 'active', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz);
create table public.client_contacts (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), client_id uuid not null references public.clients(id), full_name text not null, email text, phone text, job_title text, is_primary boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz, unique nulls not distinct (client_id, email));
create table public.lead_sources (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), name text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz, unique (organization_id, name));
create table public.lead_statuses (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), name text not null, position smallint not null default 0 check (position >= 0), is_closed boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz, unique (organization_id, name));
create table public.leads (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), client_id uuid references public.clients(id), source_id uuid references public.lead_sources(id), status_id uuid references public.lead_statuses(id), name text not null, email text, company text, estimated_value numeric(12,2) check (estimated_value >= 0), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz);
create table public.lead_notes (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), lead_id uuid not null references public.leads(id), body text not null check (char_length(body) > 0), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz);
create table public.lead_activities (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), lead_id uuid not null references public.leads(id), activity_type text not null, occurred_at timestamptz not null default now(), metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz);

create table public.projects (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), client_id uuid not null references public.clients(id), name text not null, status public.project_status not null default 'planned', start_date date, due_date date, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz, check (due_date is null or start_date is null or due_date >= start_date));
create table public.tasks (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), project_id uuid references public.projects(id), assignee_id uuid references auth.users(id), title text not null, description text, status public.task_status not null default 'todo', priority public.priority not null default 'medium', due_at timestamptz, completed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz);
create table public.task_comments (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), task_id uuid not null references public.tasks(id), body text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz);
create table public.calendar_events (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), client_id uuid references public.clients(id), project_id uuid references public.projects(id), title text not null, starts_at timestamptz not null, ends_at timestamptz not null, attendees uuid[] not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz, check (ends_at > starts_at));

create table public.quotes (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), client_id uuid not null references public.clients(id), quote_number text not null, status text not null check (status in ('draft','sent','accepted','rejected','expired')), total numeric(12,2) not null default 0 check (total >= 0), expires_at date, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz, unique (organization_id, quote_number));
create table public.invoices (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), client_id uuid not null references public.clients(id), quote_id uuid references public.quotes(id), invoice_number text not null, status text not null check (status in ('draft','sent','paid','void','overdue')), total numeric(12,2) not null default 0 check (total >= 0), due_date date, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz, unique (organization_id, invoice_number));
create table public.payments (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), invoice_id uuid not null references public.invoices(id), amount numeric(12,2) not null check (amount > 0), paid_at timestamptz not null default now(), provider_reference text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz);
create table public.documents (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), client_id uuid references public.clients(id), project_id uuid references public.projects(id), name text not null, storage_path text not null, mime_type text, size_bytes bigint check (size_bytes >= 0), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz, unique (organization_id, storage_path));

create table public.marketing_campaigns (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), client_id uuid not null references public.clients(id), name text not null, channel public.campaign_channel not null, status public.campaign_status not null default 'draft', budget numeric(12,2) check (budget >= 0), starts_at timestamptz, ends_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz, check (ends_at is null or starts_at is null or ends_at >= starts_at));
create table public.google_ads_campaigns (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), marketing_campaign_id uuid not null references public.marketing_campaigns(id), external_campaign_id text, daily_budget numeric(12,2) check (daily_budget >= 0), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz, unique (organization_id, external_campaign_id));
create table public.meta_campaigns (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), marketing_campaign_id uuid not null references public.marketing_campaigns(id), external_campaign_id text, objective text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz, unique (organization_id, external_campaign_id));
create table public.seo_projects (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), client_id uuid not null references public.clients(id), project_id uuid references public.projects(id), website_url text not null, status public.project_status not null default 'planned', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz);
create table public.seo_keywords (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), seo_project_id uuid not null references public.seo_projects(id), keyword text not null, target_url text, search_volume integer check (search_volume >= 0), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz, unique (seo_project_id, keyword));
create table public.keyword_rankings (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), seo_keyword_id uuid not null references public.seo_keywords(id), rank integer not null check (rank > 0), recorded_on date not null default current_date, search_engine text not null default 'google', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz, unique (seo_keyword_id, recorded_on, search_engine));
create table public.backlinks (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), seo_project_id uuid not null references public.seo_projects(id), source_url text not null, target_url text not null, domain_authority numeric(5,2) check (domain_authority between 0 and 100), discovered_at timestamptz not null default now(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz, unique (seo_project_id, source_url, target_url));
create table public.competitors (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), client_id uuid references public.clients(id), seo_project_id uuid references public.seo_projects(id), name text not null, website_url text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz);
create table public.website_audits (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), seo_project_id uuid not null references public.seo_projects(id), score numeric(5,2) check (score between 0 and 100), findings jsonb not null default '[]'::jsonb, audited_at timestamptz not null default now(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz);

create table public.prompt_library (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), name text not null, template text not null, category text, variables jsonb not null default '[]'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz, unique (organization_id, name));
create table public.knowledge_base (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), title text not null, content text not null, source_url text, embedding jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz);
create table public.ai_generations (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), prompt_id uuid references public.prompt_library(id), model text not null, input jsonb not null default '{}'::jsonb, output jsonb not null default '{}'::jsonb, tokens_used integer check (tokens_used >= 0), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz);
create table public.notifications (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), user_id uuid not null references auth.users(id), title text not null, body text, read_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz);
create table public.activity_logs (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), actor_id uuid references auth.users(id), action text not null, entity_type text not null, entity_id uuid, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz);
create table public.integrations (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), provider text not null, status text not null check (status in ('connected','disconnected','error')), configuration jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz, unique (organization_id, provider));
create table public.api_keys (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), name text not null, key_prefix text not null, key_hash text not null, last_used_at timestamptz, expires_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz, unique (organization_id, key_hash));
create table public.usage_tracking (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), metric text not null, quantity numeric(14,3) not null check (quantity >= 0), recorded_at timestamptz not null default now(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), deleted_at timestamptz);

create index on public.organization_members (user_id, organization_id) where deleted_at is null;
create index on public.clients (organization_id, name) where deleted_at is null;
create index on public.leads (organization_id, status_id, created_at desc) where deleted_at is null;
create index on public.projects (organization_id, client_id, status) where deleted_at is null;
create index on public.tasks (organization_id, assignee_id, due_at) where deleted_at is null;
create index on public.marketing_campaigns (organization_id, client_id, status) where deleted_at is null;
create index on public.seo_keywords (organization_id, seo_project_id) where deleted_at is null;
create index on public.keyword_rankings (seo_keyword_id, recorded_on desc) where deleted_at is null;
create index on public.notifications (user_id, read_at, created_at desc) where deleted_at is null;
create index on public.activity_logs (organization_id, created_at desc) where deleted_at is null;
create index on public.usage_tracking (organization_id, metric, recorded_at desc) where deleted_at is null;

create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;
create or replace function public.is_organization_member(p_organization_id uuid) returns boolean language sql stable security definer set search_path = public as $$ select exists (select 1 from public.organization_members where organization_id = p_organization_id and user_id = auth.uid() and deleted_at is null); $$;
create or replace function public.is_organization_editor(p_organization_id uuid) returns boolean language sql stable security definer set search_path = public as $$ select exists (select 1 from public.organization_members where organization_id = p_organization_id and user_id = auth.uid() and member_role in ('owner', 'admin', 'member') and deleted_at is null); $$;
create or replace function public.validate_organization_access() returns trigger language plpgsql security definer set search_path = public as $$ begin if current_setting('app.organization_bootstrap', true) is distinct from new.organization_id::text and not public.is_organization_member(new.organization_id) then raise exception 'Organization access denied' using errcode = '42501'; end if; if new.created_by is null then new.created_by := auth.uid(); end if; return new; end; $$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles (id, full_name, created_by) values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', ''), new.id) on conflict (id) do nothing; return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.log_activity(p_organization_id uuid, p_action text, p_entity_type text, p_entity_id uuid default null, p_metadata jsonb default '{}'::jsonb) returns uuid language plpgsql security definer set search_path = public as $$ declare v_id uuid; begin if not public.is_organization_member(p_organization_id) then raise exception 'Organization access denied' using errcode = '42501'; end if; insert into public.activity_logs (organization_id, actor_id, action, entity_type, entity_id, metadata, created_by) values (p_organization_id, auth.uid(), p_action, p_entity_type, p_entity_id, p_metadata, auth.uid()) returning id into v_id; return v_id; end; $$;
create or replace function public.create_client(p_organization_id uuid, p_name text, p_website text default null, p_industry text default null) returns public.clients language plpgsql security definer set search_path = public as $$ declare v_client public.clients; begin if not public.is_organization_member(p_organization_id) then raise exception 'Organization access denied' using errcode = '42501'; end if; insert into public.clients (organization_id, name, website, industry, created_by) values (p_organization_id, p_name, p_website, p_industry, auth.uid()) returning * into v_client; perform public.log_activity(p_organization_id, 'created', 'client', v_client.id, jsonb_build_object('name', p_name)); return v_client; end; $$;
create or replace function public.update_client(p_client_id uuid, p_name text default null, p_website text default null, p_industry text default null, p_lifecycle_status text default null) returns public.clients language plpgsql security definer set search_path = public as $$ declare v_client public.clients; begin select * into v_client from public.clients where id = p_client_id and deleted_at is null; if not found or not public.is_organization_member(v_client.organization_id) then raise exception 'Client not found or access denied' using errcode = '42501'; end if; update public.clients set name = coalesce(p_name, name), website = coalesce(p_website, website), industry = coalesce(p_industry, industry), lifecycle_status = coalesce(p_lifecycle_status::public.lifecycle_status, lifecycle_status) where id = p_client_id returning * into v_client; perform public.log_activity(v_client.organization_id, 'updated', 'client', v_client.id); return v_client; end; $$;
create or replace function public.delete_client(p_client_id uuid) returns void language plpgsql security definer set search_path = public as $$ declare v_org uuid; begin select organization_id into v_org from public.clients where id = p_client_id and deleted_at is null; if v_org is null or not public.is_organization_member(v_org) then raise exception 'Client not found or access denied' using errcode = '42501'; end if; update public.clients set deleted_at = now() where id = p_client_id; perform public.log_activity(v_org, 'deleted', 'client', p_client_id); end; $$;
create or replace function public.create_lead(p_organization_id uuid, p_name text, p_email text default null, p_company text default null, p_source_id uuid default null, p_status_id uuid default null, p_estimated_value numeric default null) returns public.leads language plpgsql security definer set search_path = public as $$ declare v_lead public.leads; begin if not public.is_organization_member(p_organization_id) then raise exception 'Organization access denied' using errcode = '42501'; end if; insert into public.leads (organization_id, name, email, company, source_id, status_id, estimated_value, created_by) values (p_organization_id, p_name, p_email, p_company, p_source_id, p_status_id, p_estimated_value, auth.uid()) returning * into v_lead; perform public.log_activity(p_organization_id, 'created', 'lead', v_lead.id); return v_lead; end; $$;
create or replace function public.update_lead(p_lead_id uuid, p_name text default null, p_email text default null, p_company text default null, p_source_id uuid default null, p_status_id uuid default null, p_estimated_value numeric default null) returns public.leads language plpgsql security definer set search_path = public as $$ declare v_lead public.leads; begin select * into v_lead from public.leads where id = p_lead_id and deleted_at is null; if not found or not public.is_organization_member(v_lead.organization_id) then raise exception 'Lead not found or access denied' using errcode = '42501'; end if; update public.leads set name = coalesce(p_name, name), email = coalesce(p_email, email), company = coalesce(p_company, company), source_id = coalesce(p_source_id, source_id), status_id = coalesce(p_status_id, status_id), estimated_value = coalesce(p_estimated_value, estimated_value) where id = p_lead_id returning * into v_lead; perform public.log_activity(v_lead.organization_id, 'updated', 'lead', v_lead.id); return v_lead; end; $$;
create or replace function public.create_task(p_organization_id uuid, p_title text, p_project_id uuid default null, p_assignee_id uuid default null, p_description text default null, p_priority text default 'medium', p_due_at timestamptz default null) returns public.tasks language plpgsql security definer set search_path = public as $$ declare v_task public.tasks; begin if not public.is_organization_member(p_organization_id) then raise exception 'Organization access denied' using errcode = '42501'; end if; insert into public.tasks (organization_id, title, project_id, assignee_id, description, priority, due_at, created_by) values (p_organization_id, p_title, p_project_id, p_assignee_id, p_description, p_priority::public.priority, p_due_at, auth.uid()) returning * into v_task; perform public.log_activity(p_organization_id, 'created', 'task', v_task.id); return v_task; end; $$;

do $$ declare t text; tenant_tables text[] := array['roles','organization_members','role_permissions','organization_subscriptions','settings','clients','client_contacts','lead_sources','lead_statuses','leads','lead_notes','lead_activities','projects','tasks','task_comments','calendar_events','quotes','invoices','payments','documents','marketing_campaigns','google_ads_campaigns','meta_campaigns','seo_projects','seo_keywords','keyword_rankings','backlinks','competitors','website_audits','prompt_library','knowledge_base','ai_generations','notifications','activity_logs','integrations','api_keys','usage_tracking']; begin
  foreach t in array tenant_tables loop
    execute format('alter table public.%I enable row level security', t);
    execute format('create policy tenant_select on public.%I for select using (public.is_organization_member(organization_id) and deleted_at is null)', t);
    execute format('create policy tenant_insert on public.%I for insert with check (public.is_organization_editor(organization_id))', t);
    execute format('create policy tenant_update on public.%I for update using (public.is_organization_editor(organization_id) and deleted_at is null) with check (public.is_organization_editor(organization_id))', t);
    execute format('create policy tenant_delete on public.%I for delete using (public.is_organization_editor(organization_id))', t);
    execute format('create trigger set_%I_updated_at before update on public.%I for each row execute function public.set_updated_at()', t, t);
    execute format('create trigger validate_%I_organization before insert or update of organization_id on public.%I for each row execute function public.validate_organization_access()', t, t);
  end loop;
end $$;
alter table public.profiles enable row level security; create policy profile_select on public.profiles for select using (id = auth.uid() and deleted_at is null); create policy profile_update on public.profiles for update using (id = auth.uid()) with check (id = auth.uid()); create trigger set_profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at();
alter table public.organizations enable row level security; create policy organization_select on public.organizations for select using (public.is_organization_member(id) and deleted_at is null); create policy organization_insert on public.organizations for insert with check (created_by = auth.uid()); create policy organization_update on public.organizations for update using (public.is_organization_member(id)) with check (public.is_organization_member(id)); create trigger set_organizations_updated_at before update on public.organizations for each row execute function public.set_updated_at();
alter table public.permissions enable row level security; create policy permission_select on public.permissions for select using (auth.role() = 'authenticated' and deleted_at is null); create trigger set_permissions_updated_at before update on public.permissions for each row execute function public.set_updated_at();
alter table public.subscription_plans enable row level security; create policy plan_select on public.subscription_plans for select using (auth.role() = 'authenticated' and deleted_at is null); create trigger set_subscription_plans_updated_at before update on public.subscription_plans for each row execute function public.set_updated_at();

-- Activity logs are visible to organization members but can only be written by
-- security-definer functions and database triggers, keeping the audit trail append-only.
drop policy tenant_insert on public.activity_logs;
drop policy tenant_update on public.activity_logs;
drop policy tenant_delete on public.activity_logs;

-- Tenant bootstrap and immutable audit trail. These functions are the only supported
-- path for creating an organization and its first owner membership.
create or replace function public.create_organization(p_name text, p_slug text)
returns public.organizations
language plpgsql security definer set search_path = public as $$
declare
  v_organization public.organizations;
  v_owner_role_id uuid;
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;
  insert into public.organizations (name, slug, created_by)
  values (p_name, p_slug, auth.uid())
  returning * into v_organization;
  perform set_config('app.organization_bootstrap', v_organization.id::text, true);
  insert into public.roles (organization_id, name, description, created_by)
  values (v_organization.id, 'Owner', 'Full organization access', auth.uid())
  returning id into v_owner_role_id;
  insert into public.organization_members (organization_id, user_id, role_id, member_role, created_by)
  values (v_organization.id, auth.uid(), v_owner_role_id, 'owner', auth.uid());
  return v_organization;
end;
$$;

create or replace function public.audit_tenant_change()
returns trigger
language plpgsql security definer set search_path = public as $$
declare
  v_record jsonb := case when tg_op = 'DELETE' then to_jsonb(old) else to_jsonb(new) end;
  v_action text := lower(tg_op);
begin
  if tg_op = 'UPDATE' and old.deleted_at is null and new.deleted_at is not null then
    v_action := 'soft_deleted';
  end if;
  insert into public.activity_logs (organization_id, actor_id, action, entity_type, entity_id, metadata, created_by)
  values (
    (v_record ->> 'organization_id')::uuid,
    auth.uid(),
    v_action,
    tg_table_name,
    (v_record ->> 'id')::uuid,
    jsonb_build_object('source', 'database_trigger'),
    auth.uid()
  );
  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

do $$
declare t text;
  audited_tables text[] := array['clients','leads','projects','tasks','marketing_campaigns','seo_projects','seo_keywords','invoices','payments','quotes','documents','integrations'];
begin
  foreach t in array audited_tables loop
    execute format('create trigger audit_%I after insert or update or delete on public.%I for each row execute function public.audit_tenant_change()', t, t);
  end loop;
end $$;

revoke all on function public.create_organization(text, text) from public;
revoke all on function public.create_client(uuid, text, text, text) from public;
revoke all on function public.update_client(uuid, text, text, text, text) from public;
revoke all on function public.delete_client(uuid) from public;
revoke all on function public.create_lead(uuid, text, text, text, uuid, uuid, numeric) from public;
revoke all on function public.update_lead(uuid, text, text, text, uuid, uuid, numeric) from public;
revoke all on function public.create_task(uuid, text, uuid, uuid, text, text, timestamptz) from public;
grant execute on function public.create_organization(text, text) to authenticated;
grant execute on function public.create_client(uuid, text, text, text) to authenticated;
grant execute on function public.update_client(uuid, text, text, text, text) to authenticated;
grant execute on function public.delete_client(uuid) to authenticated;
grant execute on function public.create_lead(uuid, text, text, text, uuid, uuid, numeric) to authenticated;
grant execute on function public.update_lead(uuid, text, text, text, uuid, uuid, numeric) to authenticated;
grant execute on function public.create_task(uuid, text, uuid, uuid, text, text, timestamptz) to authenticated;
